### ISSUE TITLE
Login to pod not working: "cannot create login data"

### ISSUE THREAD

**Issue by tarator** [Debakel/feedDiasp#28]
Hi,

when trying to run the script I get the following error:

    Login as dummyuser to https://pod.somepod.com
    Failed to login: cannot create login data (caused by: 'NoneType' object has no attribute 'group'
    Traceback (most recent call last):
      File "myscript.py", line 8, in <module>
        bot.publish()
      File "/usr/local/lib/python2.7/dist-packages/feeddiasp/FeedDiasp.py", line 58, in publish
       self.diasp.login()
      File "/usr/local/lib/python2.7/dist-packages/feeddiasp/Diasp.py", line 24, in login
        raise LoginException(str(e))
    feeddiasp.Diasp.LoginException: cannot create login data (caused by: 'NoneType' object has no attribute 'group'

**Comment by echarp** [comment]
Possibly some evolutions to diaspora, which need to be reflected into this project?

**Comment by FacundoAcevedo** [comment]
Try to update *diaspy-api*
`pip install --upgrade diaspy-api`
