### ISSUE TITLE
Not able to connect to server

### ISSUE THREAD

**Issue by PolynomialDivision** [Debakel/feedDiasp#4]
Hi,
when I'm trying to connect to a server I'm getting an error message:

```
Failed to login: ('Connection aborted.', ResponseNotReady())
Traceback (most recent call last):
  File "__init__.py", line 16, in <module>
    bot.publish()
  File "/home/pi/feedDiasp/feedDiasp/FeedDiasp.py", line 52, in publish
    self.diasp.login()
  File "/home/pi/feedDiasp/feedDiasp/Diasp.py", line 20, in login
    raise LoginException(str(e))
feedDiasp.Diasp.LoginException: ('Connection aborted.', ResponseNotReady())
```

**Comment by Debakel** [comment]
Hi, this should be fixed with the newest version of [diaspy](https://github.com/marekjm/diaspy).
