### ISSUE TITLE
Failed to login: 'NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by ghost** [Debakel/feedDiasp#6]
Hi,

Trying to login I get the following errors. I have the last version of feedparser, facepy, feedDiasp and diaspy.

```
$ submit.py
#!/usr/bin/env python
from feedDiasp.FeedDiasp import FeedDiasp
from feedDiasp.FBParser import FBParser
from feedDiasp.RSSParser import RSSParser

#Sync posts from a RSS feed
rss = RSSParser(url='https://infos.mytux.fr/rss')
bot = FeedDiasp(parser=rss, pod='https://framasphere.org', username='journalduhacker', password='R34lLyS3cr3T', db='posts.txt')
bot.publish()
$ ./submit.py 
Login as journalduhacker to https://framasphere.org
Failed to login: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "./submit.py", line 9, in <module>
    bot.publish()
  File "/home/chaica/progra/python/feedDiasp/feedDiasp/FeedDiasp.py", line 56, in publish
    self.diasp.login()
  File "/home/chaica/progra/python/feedDiasp/feedDiasp/Diasp.py", line 23, in login
    raise LoginException(str(e))
feedDiasp.Diasp.LoginException: 'NoneType' object has no attribute 'group'
```

**Comment by Debakel** [comment]
Which version of `diaspy` do you use? The one in PyPi is not up to date. Please clone directly from https://github.com/marekjm/diaspy.

**Comment by ghost** [comment]
Ok I updated the version with a current clone of the repository. Now I do have this issue: 

```
 ./submit.py 
Login as journalduhacker to https://framasphere.org
Traceback (most recent call last):
  File "./submit.py", line 9, in <module>
    bot.publish()
  File "/home/chaica/progra/python/feedDiasp/feedDiasp/FeedDiasp.py", line 59, in publish
    for post in posts:
TypeError: 'instancemethod' object is not iterable
```

**Comment by Debakel** [comment]
Try updating `feedDiasp`. Commit 5a4b42557f1e0a4932b6b304eff9a5513d80b425 should solve this issue.

**Comment by ghost** [comment]
It worked! I'm now able to send my rss feed to Diaspora*, thanks a lot!
